#!/bin/bash

while getopts "fbag" opt; do
  case $opt in
    f)
      echo "First Time Setup"
      first
      ;;
    b)
      echo "Install/Setup Brew Packages"
      brew
      ;;
    a)
	  echo "Getting Standard Applications"
	  getmacapps
	  ;;
	g)
      echo "Git Config"
      gitconfig
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done


function_name () { 
	command -v brew >/dev/null 2>&1 || `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`
	brew install git bash-completion
	brew install rbenv ruby-build
	brew install postgres
	brew install redis
	brew install rabbitmq
	
} 



ln -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" /usr/local/bin/subl
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
brew install git bash-completion

git config --global user.name "Zachary Daniel"
git config --global user.email "zachary.s.daniel@gmail.com"